version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - docker.env
    depends_on:
      - postgres
    ports:
      - "8080:8000"
    volumes:
      - ./temp/films:/lewdlocale/films
    networks:
      lewdlocale:
  
  indexer:
    build:
      context: .
      dockerfile: ./indexer/Dockerfile
    env_file:
      - docker.env
    depends_on:
      - postgres
    networks:
      lewdlocale:
    
  downloader:
    build:
      context: .
      dockerfile: ./downloader/Dockerfile
    env_file:
      - docker.env
    depends_on:
      - postgres
    networks:
      lewdlocale:


  postgres:
    image: postgres:15.3-alpine
    env_file:
      - .env
    volumes:
      - ./temp/pg-data:/var/lib/postgresql/data # replace with on-system path
   # ports:
   #  - "5433:5432" # for external access
    restart: always
    hostname: postgres
    networks:
      lewdlocale:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lewdlocale"]
      interval: 10s
      timeout: 5s
      retries: 5
  
networks:
  lewdlocale:
    driver: bridge