version: "3.9"
services:
  downloader:
    build: .
    env_file:
      - .env
    args: 
      SERVICE: downloader
  
  indxer:
    build: .
    env_file:
      - .env
    args: 
      SERVICE: indexer
  
  database:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}