/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  'MENU_CHANGE_HAS_SUB_ITEM_STATUS';

/* LIBRARY */
export const FETCH_ACTRESSES_REQUEST = "FETCH_ACTRESSES_REQUEST";
export const SET_ACTRESSES = 'SET_ACTRESSES';
export const FETCH_ACTRESSES_SUCCESS = "FETCH_ACTRESSES_SUCCESS";
export const FETCH_ACTRESSES_FAILURE = "FETCH_ACTRESSES_FAILURE";

export const SET_FILMS = "SET_FILMS";
export const FETCH_FILMS_FAILURE = "FETCH_FILM_FAILURE"
export const FETCH_FILMS_REQUEST = "FETCH_FILM_REQUEST"
export const FETCH_FILMS_SUCCESS = "FETCH_FILM_SUCCESS"